/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tournamentapp;

import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author Yogi
 */
public class ChoosePlayerPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlayerViewPanelText
     */
    public ChoosePlayerPanel(Player player) {
        initComponents();
        NickTextField.setText(player.toString());
        NameTextField.setText(player.getFirstName());
        SecondNameTextField.setText(player.getLastName());
        CityTextField.setText(player.getCity());
        this.setVisible(true);
        
    }

    public JRadioButton getCheckButton() {
        return CheckButton;
    }

    public JLabel getCityTextField() {
        return CityTextField;
    }

    public JLabel getNameTextField() {
        return NameTextField;
    }

    public JLabel getNickTextField() {
        return NickTextField;
    }

    public JLabel getSecondNameTextField() {
        return SecondNameTextField;
    }

    public Player getPlayer(){
        
        Player player = new Player(this.getNameTextField().getText(),
                                            this.getSecondNameTextField().getText(),
                                            this.getNickTextField().getText(),
                                            this.getCityTextField().getText());
        
        return player;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NickTextField = new javax.swing.JLabel();
        NameTextField = new javax.swing.JLabel();
        SecondNameTextField = new javax.swing.JLabel();
        CityTextField = new javax.swing.JLabel();
        CheckButton = new javax.swing.JRadioButton();

        NickTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SecondNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CityTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CheckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NickTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SecondNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecondNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NickTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CheckButton;
    private javax.swing.JLabel CityTextField;
    private javax.swing.JLabel NameTextField;
    private javax.swing.JLabel NickTextField;
    private javax.swing.JLabel SecondNameTextField;
    // End of variables declaration//GEN-END:variables
}
