/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tournamentapp;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;

/**
 *
 * @author Yogi
 */
public class MatchViewPanel extends javax.swing.JPanel {

    private Group group;
    private List<SimpleMatchPane> simpleMatchPaneList = new ArrayList<SimpleMatchPane>(); 
    
    public MatchViewPanel(Group group) {
        initComponents();
        this.group = group;
        
        //GridLayout newLayout = new GridLayout(group.getMatchList().size(),1);
        BoxLayout newLayout = new BoxLayout(this,BoxLayout.PAGE_AXIS);
        this.setLayout(newLayout);
        
        for(Match match : group.getMatchList()){
            simpleMatchPaneList.add(new SimpleMatchPane(match));
        }
        
        this.refreshMatchPaint();
        
        this.setVisible(true);
    }
    
    public void updateStatistic(){
        
        this.group.resetAllStatistic();
        
        for(SimpleMatchPane simpleMatchPane: simpleMatchPaneList){
            simpleMatchPane.setScore();
        }
        group.updateStatistic();
    }
    
    public void refreshMatchPaint(){
        for(SimpleMatchPane simpleMatchPane : simpleMatchPaneList){
            this.add(simpleMatchPane);
        }
    }

    public List<SimpleMatchPane> getSimpleMatchPaneList() {
        return simpleMatchPaneList;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
